#!/usr/bin/env python3
"""Tiny TLS echo / HTTP server for the uc386 MP TLS rig.

Listens on TLS port (default 8443), accepts one TLS handshake at a
time, sends a fixed `TLS_RIG_OK <client-bytes>` response on the
first read, then closes. Single-threaded and short-lived so the
rig can run it as a background process and reap it cleanly.

Cert + key are read from the same directory as this script
(test-server.crt / test-server.key, generated by run-tls-rig.sh
via openssl).
"""

import argparse
import socket
import ssl
import sys
import threading
import time
from pathlib import Path


HERE = Path(__file__).resolve().parent


def serve_one(port: int, cert: Path, key: Path, *, max_seconds: float = 60.0) -> int:
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(certfile=str(cert), keyfile=str(key))
    # axtls speaks TLSv1.0 only (CONFIG_SSL_PROT_LOW), with RSA-AES-CBC
    # ciphers. Modern OpenSSL drops these from the defaults, so we
    # force-enable them here. The @SECLEVEL=0 suffix disables the
    # security-level gate that otherwise rejects TLSv1.0 + 1024-bit
    # RSA on OpenSSL 1.1+; LibreSSL ignores the suffix harmlessly.
    # Safe in this rig — the only client is uc386 axtls, and we
    # generate a fresh self-signed key per run.
    try:
        ctx.minimum_version = ssl.TLSVersion.TLSv1
        ctx.maximum_version = ssl.TLSVersion.TLSv1
    except AttributeError:
        pass  # older Pythons
    try:
        ctx.set_ciphers("AES128-SHA:AES256-SHA:@SECLEVEL=0")
    except ssl.SSLError:
        # LibreSSL doesn't grok @SECLEVEL — try without.
        ctx.set_ciphers("AES128-SHA:AES256-SHA")

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(("0.0.0.0", port))
    sock.listen(1)
    sock.settimeout(max_seconds)
    print(f"[tls-server] listening on 0.0.0.0:{port}", flush=True)

    try:
        client, addr = sock.accept()
    except socket.timeout:
        print(f"[tls-server] timeout waiting for connection", flush=True)
        return 1
    print(f"[tls-server] connection from {addr}", flush=True)

    client.settimeout(max_seconds)
    try:
        tls = ctx.wrap_socket(client, server_side=True)
    except ssl.SSLError as e:
        print(f"[tls-server] handshake failed: {e}", flush=True)
        client.close()
        return 2
    print(f"[tls-server] handshake ok, cipher={tls.cipher()}", flush=True)

    try:
        data = tls.read(64)
    except (ssl.SSLError, socket.timeout) as e:
        print(f"[tls-server] read failed: {e}", flush=True)
        tls.close()
        return 3

    msg = b"TLS_RIG_OK " + data + b"\n"
    tls.write(msg)
    print(f"[tls-server] sent {msg!r}", flush=True)

    try:
        tls.close()
    except Exception:
        pass
    sock.close()
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8443)
    ap.add_argument("--cert", type=Path, default=HERE / "test-server.crt")
    ap.add_argument("--key", type=Path, default=HERE / "test-server.key")
    ap.add_argument("--max-seconds", type=float, default=60.0)
    args = ap.parse_args()
    return serve_one(args.port, args.cert, args.key, max_seconds=args.max_seconds)


if __name__ == "__main__":
    sys.exit(main())
