#!/usr/bin/env python3
"""Build each addon with host gcc + uc386 + (optional) watcom/djgpp,
report sizes side-by-side. Output is a markdown table written to
`addons/results.md`.

Today only gcc + uc386 are wired. Watcom (`wcc386`) and djgpp need
cross-compilers we don't currently install; the table reserves
columns for them so the format is stable.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ADDONS_ROOT = REPO_ROOT / "addons"
LIB_INCLUDE = REPO_ROOT / "lib" / "include"


def find_addons() -> list[Path]:
    """Each addon dir under addons/gnu/ that has a main.c counts."""
    out: list[Path] = []
    for sub in sorted((ADDONS_ROOT / "gnu").iterdir()):
        if not sub.is_dir() or sub.name.startswith("_"):
            continue
        if (sub / "main.c").exists():
            out.append(sub)
    return out


def build_gcc(addon: Path) -> int | None:
    """Build addon/main.c with host gcc; return ELF size or None on fail."""
    if not shutil.which("gcc"):
        return None
    out = REPO_ROOT / "build" / "compare" / addon.name
    out.mkdir(parents=True, exist_ok=True)
    bin_path = out / "gcc.bin"
    proc = subprocess.run(
        ["gcc", "-O2", "-w", str(addon / "main.c"), "-o", str(bin_path)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return None
    return bin_path.stat().st_size


def build_uc386(addon: Path) -> int | None:
    """Build via the harness path: uc386 → bundle libc → nasm → bin size."""
    out = REPO_ROOT / "build" / "compare" / addon.name
    out.mkdir(parents=True, exist_ok=True)
    asm_path = out / "uc386.asm"
    proc = subprocess.run(
        [sys.executable, "-m", "uc386.main", str(addon / "main.c"),
         "-o", str(asm_path), "-I", str(LIB_INCLUDE)],
        capture_output=True, text=True, cwd=REPO_ROOT,
    )
    if proc.returncode != 0:
        return None
    bin_path = out / "uc386.bin"
    proc = subprocess.run(
        ["nasm", "-f", "bin", str(asm_path), "-o", str(bin_path)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return None
    return bin_path.stat().st_size


def build_watcom(addon: Path) -> int | None:
    if not shutil.which("wcc386"):
        return None
    return None  # not wired


def build_djgpp(addon: Path) -> int | None:
    if not shutil.which("i586-pc-msdosdjgpp-gcc"):
        return None
    return None  # not wired


def main() -> int:
    ap = argparse.ArgumentParser(prog="addons.harness.compare")
    ap.add_argument("--write", action="store_true",
                    help="write results to addons/results.md (default: stdout)")
    args = ap.parse_args()

    addons = find_addons()
    rows: list[tuple[str, int | None, int | None, int | None, int | None]] = []
    for addon in addons:
        gcc_sz = build_gcc(addon)
        uc_sz = build_uc386(addon)
        wcc_sz = build_watcom(addon)
        djgpp_sz = build_djgpp(addon)
        rows.append((addon.name, uc_sz, gcc_sz, wcc_sz, djgpp_sz))

    def cell(n: int | None) -> str:
        return f"{n:,}" if n is not None else "—"

    md = ["# Build comparison: uc386 vs gcc / Watcom / DJGPP", "",
          "Sizes in bytes (raw .bin / ELF). uc386 builds to a flat ",
          "i386 binary that runs under dos_emu; gcc builds a host ",
          "ELF (different format — size comparison is rough). Watcom ",
          "and DJGPP columns are reserved for when the cross-",
          "compilers are installed.", "",
          "| Tool | uc386 | gcc (host ELF) | Watcom wcc386 | DJGPP |",
          "|------|-------|----------------|---------------|-------|"]
    for name, uc_sz, gcc_sz, wcc_sz, djgpp_sz in rows:
        md.append(
            f"| {name} | {cell(uc_sz)} | {cell(gcc_sz)} | {cell(wcc_sz)} | {cell(djgpp_sz)} |"
        )
    md.append("")
    md.append("_Generated by `python -m addons.harness.compare --write`._")
    text = "\n".join(md)
    if args.write:
        out_path = ADDONS_ROOT / "results.md"
        out_path.write_text(text + "\n")
        print(f"Wrote {out_path}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
